// Mocks generated by Mockito 5.4.6 from annotations
// in maingames_flutter_test/test/auth/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:maingames_flutter_test/core/model/base_response.dart' as _i2;
import 'package:maingames_flutter_test/src/features/auth/data/data_sources/auth_data_source.dart'
    as _i3;
import 'package:maingames_flutter_test/src/features/auth/data/dtos/request/login_request_dto.dart'
    as _i6;
import 'package:maingames_flutter_test/src/features/auth/data/dtos/response/login_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDatasource extends _i1.Mock implements _i3.AuthDatasource {
  MockAuthDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<_i5.LoginResponseDto?>> login(
          _i6.LoginRequestDto? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [param],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<_i5.LoginResponseDto?>>.value(
            _FakeBaseResponse_0<_i5.LoginResponseDto?>(
          this,
          Invocation.method(
            #login,
            [param],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.LoginResponseDto?>>);
}
